sudo: required
dist: xenial
services:
  - docker
language: python
matrix:
  include:
    - python: "3.7.1"
      env: DEPLOY_DOCKER_IMAGE=true
install:
  - "make install"
script:
  - "make test"
  - "make image"
after_success:
  # Docker Hub (no-op for PRs and DEPLOY_DOCKER_IMAGE=false)
  - make travis-docker-deploy
env:
  global:
    - DEPLOY_DOCKER_IMAGE=false  # disable docker push in regular test matrix
    # DOCKER_USERNAME and DOCKER_PASSWORD
    - secure: "j7TljyQ796gFiyeKz/E23sOy+oCkjtsopb+9alJIVhr7rqzgCw3vVSYoo0sjUnlCLylqPyFiJ7nPZcyLmcOpxXtnrozUlAvqLjAXCEsmzHvYaxsS2rcOsDFVUCN5Kvy8wVpV2N/m/ovKcqOydYibxeJsjP0GeduhM8OSkrrPiHlYaNk3KfT57TxkjT5mLLPdWmAIJ9/29NyzhvqzWjg5OhfnT/Buoi0XgV/bTIBnevAQ5qj+HrJiRSiWbtXefREQ/WWGkuzL2Q9vdckNritwlaIldtYKM/LA/MUGYllX/mJxrqV1MXl8H7rhJmr6OyQLeJWUn0KWS6QISMMhVlInX/LOTYuJowbREuoJ8OgQSfnokMcAC87xoZY/LmN+3n8vfEVO34PbYiMfZ/SAWjsGdy4jcdl/r3rA/RRUmrFr52YhmrCyqcHQqtQddBEnP1QrpvSYnUTsGf3caeAL+ifTF5pZaoDpZtwQCB5BvZV6VmBOJj5UBdoszoXMNVf1BExBJsEVLGl4RaTtl28RcWR6sWpeWT7EP6EYhajlZ6PcCrNOgY/jWiTRh7lC3/cDQfKYmYLSsf+GsgEonHho00db2aA+SN1R6b24Eh8IF6SaH+MYgt/hIgI9n3Q1Qw3EXB/OJ3t0nrW9u+HVDnBrM076m2h56xQjuMdYHodTyHHgB+k="
