apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: "registry-schemas"
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 3
  config:
    # http://kafka.apache.org/documentation/#topicconfigs
    cleanup.policy: "compact"
---
